name: Track Virginia Bills

on:
  # Run daily at 8 AM ET (1 PM UTC)
  schedule:
    - cron: '0 13 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Run on push to main (for testing)
  push:
    branches: [ main ]

jobs:
  track-bills:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Needed to commit changes
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium
      
      - name: Run bill tracker
        run: |
          python track_bills.py
        env:
          TZ: 'America/New_York'
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/ docs/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update bill tracking data - $(date +'%Y-%m-%d %H:%M')" && git push)
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          enable_jekyll: false
